#pragma once

#ifndef	YCSR_VERSION_INCLUDED
#define YCSR_VERSION_INCLUDED

#define MAKE_STR_HELPER(x) #x
#define MAKE_STR(x) MAKE_STR_HELPER(x)

#define YCSR_VERSION_MAJOR		1
#define YCSR_VERSION_MINOR		0
#define YCSR_VERSION_PATCH		0
#define YCSR_VERSION_BETA		0
#define YCSR_VERSION_VERSTRING	MAKE_STR(YCSR_VERSION_MAJOR) "." MAKE_STR(YCSR_VERSION_MINOR) "." MAKE_STR(YCSR_VERSION_PATCH) "." MAKE_STR(YCSR_VERSION_BETA)

#endif
